# Generated by Django 6.0.7 on 2026-07-30 19:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('unit', models.CharField(default='Tablets', max_length=50)),
                ('daily_consumption', models.PositiveIntegerField(default=10, help_text='Average daily usage units')),
                ('lead_time_days', models.PositiveIntegerField(default=7, help_text='Supplier lead time in days')),
                ('safety_stock', models.PositiveIntegerField(default=50, help_text='Safety stock cushion units')),
                ('max_level', models.PositiveIntegerField(default=300, help_text='Maximum stock capacity limit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PharmacySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100)),
                ('initial_quantity', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('manufacture_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('received_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='app.medication')),
            ],
            options={
                'ordering': ['expiry_date'],
            },
        ),
        migrations.AddField(
            model_name='medication',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='app.pharmacysection'),
        ),
        migrations.CreateModel(
            name='StockAuditLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(editable=False, max_length=64, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.CharField(choices=[('RECEIVE', 'Stock Restocked'), ('DISPENSE_FEFO', 'Dispensed (FEFO)'), ('ADJUSTMENT', 'Physical Audit Count Adjustment'), ('TRANSFER', 'Pharmacy Section Transfer'), ('QUARANTINE', 'Expired Batch Quarantine')], max_length=30)),
                ('previous_qty', models.IntegerField()),
                ('change_qty', models.IntegerField()),
                ('new_qty', models.IntegerField()),
                ('reason', models.TextField(blank=True)),
                ('previous_hash', models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000', max_length=64)),
                ('current_hash', models.CharField(editable=False, max_length=64)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.medicationbatch')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='app.medication')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
