# Generated by Django 6.0.7 on 2026-07-30 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_medication_pharmacysection_medicationbatch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='stockauditledger',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='stockauditledger',
            name='change_qty',
        ),
        migrations.RemoveField(
            model_name='stockauditledger',
            name='medication',
        ),
        migrations.RemoveField(
            model_name='stockauditledger',
            name='new_qty',
        ),
        migrations.RemoveField(
            model_name='stockauditledger',
            name='previous_qty',
        ),
        migrations.RemoveField(
            model_name='stockauditledger',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'System Administrator'), ('PHARMACIST', 'Pharmacist'), ('MANAGER', 'Inventory Manager')], default='PHARMACIST', max_length=20),
        ),
        migrations.AddField(
            model_name='medication',
            name='annual_demand',
            field=models.PositiveIntegerField(default=3600, help_text='Configured annual demand units'),
        ),
        migrations.AddField(
            model_name='medication',
            name='holding_cost',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Annual holding cost H per unit', max_digits=10),
        ),
        migrations.AddField(
            model_name='medication',
            name='ordering_cost',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Ordering cost S per PO', max_digits=10),
        ),
        migrations.AddField(
            model_name='medication',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Unit purchase price', max_digits=10),
        ),
        migrations.AddField(
            model_name='stockauditledger',
            name='affected_entity',
            field=models.CharField(default='Medication', max_length=100),
        ),
        migrations.AddField(
            model_name='stockauditledger',
            name='after_data',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AddField(
            model_name='stockauditledger',
            name='before_data',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AddField(
            model_name='stockauditledger',
            name='entity_pk',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='stockauditledger',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockauditledger',
            name='user_identity',
            field=models.CharField(default='system', max_length=150),
        ),
        migrations.AlterField(
            model_name='medication',
            name='max_level',
            field=models.PositiveIntegerField(default=500, help_text='Maximum capacity limit'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='safety_stock',
            field=models.PositiveIntegerField(default=50, help_text='Safety stock (Minimum Level)'),
        ),
        migrations.AlterField(
            model_name='stockauditledger',
            name='action_type',
            field=models.CharField(choices=[('STOCK_RECEIPT', 'Stock Goods Receipt'), ('DISPENSE_FEFO', 'Dispensed (FEFO)'), ('STOCK_ADJUSTMENT', 'Physical Count Adjustment'), ('PO_CREATE', 'Purchase Order Drafted'), ('PO_APPROVE', 'Purchase Order Approved'), ('USER_LOGIN', 'User Session Login'), ('CONFIG_CHANGE', 'System Configuration Change'), ('QUARANTINE', 'Expired Batch Isolation')], max_length=30),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('RECEIVED', 'Received / Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='app.supplier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.PositiveIntegerField()),
                ('eoq_recommended_qty', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.medication')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.purchaseorder')),
            ],
        ),
        migrations.AddField(
            model_name='medication',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medications', to='app.supplier'),
        ),
        migrations.AddField(
            model_name='medicationbatch',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.supplier'),
        ),
    ]
