# Generated by Django 6.0.7 on 2026-08-09 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_supplier_remove_stockauditledger_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='selling_price_per_unit',
            field=models.DecimalField(decimal_places=2, default=200.0, help_text='Selling price per unit in Nigerian Naira', max_digits=10),
        ),
        migrations.CreateModel(
            name='SalesTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_ref', models.CharField(editable=False, max_length=50, unique=True)),
                ('total_amount_naira', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('patient_info', models.CharField(blank=True, help_text='Patient name or prescription reference', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pharmacist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesTransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.PositiveIntegerField()),
                ('unit_price_naira', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal_naira', models.DecimalField(decimal_places=2, max_digits=12)),
                ('medication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.medication')),
                ('sales_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.salestransaction')),
            ],
            options={
                'ordering': ['-sales_transaction__created_at', 'medication__name'],
            },
        ),
    ]
