# Generated by Django 6.0.7 on 2026-08-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_medication_selling_price_per_unit_salestransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestransaction',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash (₦)'), ('POS_CARD', 'POS / Debit Card (₦)'), ('TRANSFER', 'Bank Transfer (₦)'), ('INSURANCE', 'Health Insurance / HMO')], default='CASH', max_length=20),
        ),
        migrations.AlterField(
            model_name='medication',
            name='holding_cost',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Annual holding cost H per unit in Nigerian Naira', max_digits=10),
        ),
        migrations.AlterField(
            model_name='medication',
            name='ordering_cost',
            field=models.DecimalField(decimal_places=2, default=500.0, help_text='Ordering cost S per PO in Nigerian Naira', max_digits=10),
        ),
        migrations.AlterField(
            model_name='medication',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Unit purchase price in Nigerian Naira', max_digits=10),
        ),
    ]
