# Generated by Django 6.0.7 on 2026-08-02 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_content_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_caused', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('rop_alert', 'Reorder Point Breach Alert'), ('out_of_stock', 'Out of Stock Alert'), ('expiry_alert', 'Expiry Warning'), ('quarantine_notice', 'Batch Quarantine Notice'), ('po_created', 'Purchase Order Drafted'), ('po_approved', 'Purchase Order Approved'), ('stock_receipt', 'Goods Receipt Intake'), ('stock_adjustment', 'Stock Audit Adjustment'), ('system_alert', 'System Alert')], default='system_alert', max_length=50),
        ),
    ]
